-- ORACLE
SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT
        c.CAR_ID,
        c.CAR_TYPE,
        TRUNC(c.DAILY_FEE * (100 - NVL(d.DISCOUNT_RATE, 0)) / 100 * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
        ON c.CAR_TYPE = d.CAR_TYPE
        AND d.DURATION_TYPE = '30일 이상'
    WHERE c.CAR_TYPE IN ('세단', 'SUV')
      AND c.CAR_ID NOT IN (
          SELECT h.CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
          WHERE h.START_DATE <= DATE '2022-11-30'
            AND h.END_DATE   >= DATE '2022-11-01'
      )
)
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;