-- ORACLE
SELECT
    TO_CHAR(ONS.SALES_DATE, 'YYYY-MM-dd') AS SALES_DATE, 
    ONS.PRODUCT_ID,
    ONS.USER_ID,
    ONS.SALES_AMOUNT
FROM ONLINE_SALE ONS
WHERE TO_CHAR(ONS.SALES_DATE, 'YYYY-MM') = '2022-03'

UNION ALL

SELECT
    TO_CHAR(OFFS.SALES_DATE, 'YYYY-MM-dd') AS SALES_DATE, 
    OFFS.PRODUCT_ID,
    NULL AS USER_ID,
    OFFS.SALES_AMOUNT
FROM OFFLINE_SALE OFFS
WHERE TO_CHAR(OFFS.SALES_DATE, 'YYYY-MM') = '2022-03'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID