-- Oracle
SELECT ANIMAL_ID, NAME
FROM (
    SELECT o.ANIMAL_ID, o.NAME, (o.DATETIME - i.DATETIME) AS PROTECT_DAYS
    FROM ANIMAL_INS i
    RIGHT OUTER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
    WHERE i.DATETIME IS NOT NULL
    ORDER BY PROTECT_DAYS DESC
)
WHERE ROWNUM <= 2;