-- MySQL
SELECT ROUND(AVG(f.LENGTH), 2) AS AVERAGE_LENGTH
FROM (
    SELECT 
        CASE 
            WHEN LENGTH IS NULL OR LENGTH < 10 THEN 10.0
            ELSE LENGTH
        END AS LENGTH
    FROM FISH_INFO
) f;