-- ORACLE
WITH HOUR_LIST AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
),
ADOPT_PER_HOUR AS (
    SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR, COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
)
SELECT H.HOUR, NVL(A.CNT, 0) AS COUNT
FROM HOUR_LIST H
LEFT JOIN ADOPT_PER_HOUR A ON H.HOUR = A.HOUR
ORDER BY H.HOUR;