-- ORACLE
-- SELECT
--     EXTRACT(YEAR FROM SALES_DATE) AS YEAR
--     , EXTRACT(MONTH FROM SALES_DATE) AS MONTH
--     , GENDER
--     , COUNT(*) AS USERS
-- FROM ONLINE_SALE I
-- LEFT JOIN USER_INFO S ON S.USER_ID = I.USER_ID
-- WHERE GENDER IS NOT NULL
-- GROUP BY EXTRACT(YEAR FROM SALES_DATE) 
--     , EXTRACT(MONTH FROM SALES_DATE) 
--     , GENDER
-- ORDER BY YEAR, MONTH, GENDER;
SELECT
    TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
    U.GENDER,
    COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE S
  ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY
    TO_CHAR(S.SALES_DATE, 'YYYY'),
    TO_CHAR(S.SALES_DATE, 'MM'),
    U.GENDER
ORDER BY
    YEAR, MONTH, GENDER;
