-- ORACLE
SELECT
    TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / T.TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S
JOIN (
    SELECT USER_ID FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
) U ON S.USER_ID = U.USER_ID
JOIN (
    SELECT COUNT(*) AS TOTAL_USERS FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
) T ON 1 = 1
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), T.TOTAL_USERS
ORDER BY YEAR, MONTH;