-- MySQL
SELECT CONCAT(q.qtr, 'Q') AS QUARTER, q.ECOLI_COUNT
FROM (
    SELECT QUARTER(DIFFERENTIATION_DATE) AS qtr, COUNT(*) AS ECOLI_COUNT
    FROM ECOLI_DATA
    GROUP BY QUARTER(DIFFERENTIATION_DATE)
) AS q
ORDER BY q.qtr;