-- ORACLE
SELECT H.HISTORY_ID,
    TRUNC(C.DAILY_FEE * (1 - NVL(P.DISCOUNT_RATE, 0) / 100) * (H.END_DATE - H.START_DATE + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
   AND (
        (P.DURATION_TYPE = '7일 이상' AND (H.END_DATE - H.START_DATE + 1) >= 7 AND (H.END_DATE - H.START_DATE + 1) < 30)
     OR (P.DURATION_TYPE = '30일 이상' AND (H.END_DATE - H.START_DATE + 1) >= 30 AND (H.END_DATE - H.START_DATE + 1) < 90)
     OR (P.DURATION_TYPE = '90일 이상' AND (H.END_DATE - H.START_DATE + 1) >= 90)
   )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;