-- Oracle
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
WHERE START_DATE >= DATE '2022-10-01'
    AND c.CAR_TYPE = '세단'
ORDER BY c.CAR_ID DESC;