-- MySQL
SELECT  A.SCORE,
        E.EMP_NO,
        E.EMP_NAME,
        E.POSITION,
        E.EMAIL
FROM (
    SELECT  EMP_NO,
            SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
) A
JOIN HR_EMPLOYEES E
  ON A.EMP_NO = E.EMP_NO
WHERE A.SCORE = (
    SELECT MAX(SCORE)
    FROM (
        SELECT  EMP_NO,
                SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = '2022'
        GROUP BY EMP_NO
    ) X
);
