-- ORACLE
-- SELECT b.CATEGORY, bs.TOTAL_SALES(SALES)
-- FROM BOOK b, 
-- LEFT JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_SALES
-- WHERE bs.SALES_DATE BETWEEN 2022-01-01 AND 2022-01-31
-- GROUP BY CATEGORY
-- ORDER BY CATEGORY;
SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;