-- Oracle
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM (
    SELECT 
        CATEGORY, PRODUCT_NAME, PRICE,
        MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
)
WHERE PRICE = MAX_PRICE
  AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;
